from langchain_core.messages import ToolMessage
import asyncio
from langchain_ollama import ChatOllama
from langchain_core.messages import SystemMessage, HumanMessage
from mcp import StdioServerParameters
from mcp.client.stdio import stdio_client
from mcp import ClientSession
from langchain_mcp_adapters.tools import load_mcp_tools
import json
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from graph.state import SOCState
async def agent3_node():
    # 1. Define how to connect
    server_params = StdioServerParameters(
        command="python",
        args=["mcp/server.py"],
        env=None
    )

    print("Connecting to MCP Server...")
    # 2. Establish the stdio connection and session
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            # Initialize the protocol
            await session.initialize()
            
            # 3. Load the tools using the active session!
            mcp_tools = await load_mcp_tools(session)
            print(f"Loaded tools: {[t.name for t in mcp_tools]}")

            # 4. Setup Qwen
            llm = ChatOllama(
                base_url="http://localhost:11434",
                model="qwen2.5:3b",
                temperature=0.1,
                num_ctx=8192
            )
            
            agent3_llm_with_tools = llm.bind_tools(mcp_tools)

            # Condensed schema to avoid flooding the context window with the full mapping
            condensed_schema = """
Key fields in wazuh-archive index:
- timestamp (text)
- agent.id, agent.name, agent.ip (text + keyword)
- rule.level (text), rule.description (text + keyword), rule.id (text), rule.groups (text)
- rule.mitre.id, rule.mitre.tactic, rule.mitre.technique (text)
- data.srcip, data.srcport, data.srcuser, data.dstuser (text + keyword)
- data.command, data.title, data.uid, data.euid (text + keyword)
- data.audit.type, data.audit.exe, data.audit.command, data.audit.acct, data.audit.res (text + keyword)
- decoder.name, decoder.parent (text + keyword)
- full_log (text + keyword)
- location (text + keyword)
- manager.name (text + keyword)
- id (text)
Note: All text fields have a .keyword subfield for exact matching.
"""
            questions = "Show all events where the rule description is exactly 'authentication failed' and the IP is '192.168.100.30'."
            prompt = [
                SystemMessage(content='''You are an OpenSearch query assistant. You MUST call search_wazuh to answer questions.

Index: wazuh-archive
Key fields: agent.name, rule.description, rule.level, data.srcip, data.dstuser, data.srcuser, data.command, full_log, timestamp

Rules:
1. ALWAYS call search_wazuh.
2. The lucene_query argument MUST be a valid Lucene query string.
3. Use double quotes around individual field values (e.g. data.srcip:"192.168.100.30").
4. DO NOT wrap the entire query in quotes.
5. Example query: rule.description:"authentication failed" AND data.srcip:"192.168.100.30"
'''),
                HumanMessage(content=questions)
            ]

            print("Invoking Qwen...")
            tool_result_collected = []
            
            # 2. Loop until Qwen is done making tool calls
            while True:
                response = await agent3_llm_with_tools.ainvoke(prompt)
                prompt.append(response)
                
                # If Qwen doesn't want to call any more tools, we have our final answer!
                if not response.tool_calls:
                    print("\n--- Final Answer ---")
                    print(response.content)
                    return {"results_round2": [{"raw_results": tool_result_collected, "analysis": response.content}]}
                
                print("\n--- Tool Calls Generated by Qwen ---")
                for tool_call in response.tool_calls:
                    print(tool_call)
                print("\n--- Executing Tool Calls ---")
                
                for tool_call in response.tool_calls:
                    print(f"Executing tool: {tool_call['name']}")
                    tool_to_run = next((t for t in mcp_tools if t.name == tool_call["name"]), None)
                    if tool_to_run: 
                        tool_result = await tool_to_run.ainvoke(tool_call["args"])
                        tool_result_collected.append(tool_result)
                        print("Tool returned result successfully")
                        tool_message = ToolMessage(
                            content=str(tool_result),
                            tool_call_id=tool_call["id"]    
                        )
                        prompt.append(tool_message)
                    else: 
                        print(f"Error: Tool {tool_call['name']} not found.")
                        tool_message = ToolMessage(
                            content=f"Error: Tool {tool_call['name']} not found.",
                            tool_call_id=tool_call["id"]
                        )
                        prompt.append(tool_message)


if __name__ == "__main__":
    # Pass a dummy state for testing the node locally
    asyncio.run(agent3_node())
