import asyncio
from langchain_ollama import ChatOllama
from langchain_core.messages import SystemMessage, HumanMessage
from mcp import StdioServerParameters
from mcp.client.stdio import stdio_client
from mcp import ClientSession
from langchain_mcp_adapters.tools import load_mcp_tools

async def main():
    # 1. Define how to connect
    server_params = StdioServerParameters(
        command="python",
        args=["mcp/server.py"],
        env=None
    )

    print("Connecting to MCP Server...")
    # 2. Establish the stdio connection and session
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            # Initialize the protocol
            await session.initialize()
            
            # 3. Load the tools using the active session!
            mcp_tools = await load_mcp_tools(session)
            print(f"Loaded tools: {[t.name for t in mcp_tools]}")

            # 4. Setup Qwen
            llm = ChatOllama(
                base_url="http://localhost:11434",
                model="qwen2.5:3b",
                temperature=0.1
            )
            
            agent3_llm_with_tools = llm.bind_tools(mcp_tools)

            mapping = await mcp_tools[0].ainvoke({"index_name":"wazuh-archive"})
            questions = "Find all alerts triggered by the agent named 'web-server-01'."
            
            prompt = [
                SystemMessage(content=f"You are an expert Threat Hunter. Translate the user's questions into OpenSearch DSL and use the msearch_tool to find the answers. You MUST set the index_name argument to exactly 'wazuh-archive'. Here is the index mapping: {mapping}"),
                HumanMessage(content=questions)
            ]

            print("Invoking Qwen...")
            response = await agent3_llm_with_tools.ainvoke(prompt)
            print(response)
            
            print("\n--- Tool Calls Generated by Qwen ---")
            for tool_call in response.tool_calls:
                print(tool_call)

if __name__ == "__main__":
    asyncio.run(main())
